<robot name="example_manipulator" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- Macros -->

    <xacro:macro name="make_box_link" params="name mass size_x size_y size_z">
        <link name="${name}">
            <inertial>
                <origin xyz="${size_x / 2} 0 0" />
                <mass value="${mass}" />
                <inertia ixx="${mass * (size_y * size_y + size_z * size_z) / 12}" ixy="0" ixz="0"
                         iyy="${mass * (size_z * size_z + size_x * size_x) / 12}" iyz="0"
                         izz="${mass * (size_x * size_x + size_y * size_y) / 12}" />
            </inertial>
            <visual>
                <origin xyz="${size_x / 2} 0 0" />
                <geometry>
                    <box size="${size_x} ${size_y} ${size_z}" />
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="make_cont_joint" params="name parent child xyz rpy effort velocity">
        <joint name="${name}" type="continuous">
            <parent link="${parent}" />
            <child link="${child}" />
            <origin xyz="${xyz}" rpy="${rpy}" />
            <axis xyz="0 0 1" />
            <limit effort="${effort}" velocity="${velocity}" />
        </joint>
        <transmission name="${name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_actuator">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- Constants -->

    <xacro:property name="TORAD" value="${3.14159265359 / 180}" />

    <!-- Links & joints -->

    <xacro:make_box_link name="body" mass="1." size_x="0.2" size_y="0.2" size_z="0.2" />

    <xacro:make_cont_joint name="shoulder" parent="body" child="upper_arm" 
                           xyz="0.2 0 0" rpy="${90 * TORAD} 0 0" 
                           effort="30." velocity="1." />

    <xacro:make_box_link name="upper_arm" mass="1." size_x="0.3" size_y="0.1" size_z="0.1" />

    <xacro:make_cont_joint name="elbow" parent="upper_arm" child="forearm" 
                           xyz="0.3 0 0" rpy="0 0 0"
                           effort="15." velocity="1." />

    <xacro:make_box_link name="forearm" mass="1." size_x="0.3" size_y="0.05" size_z="0.05" />

    <xacro:make_cont_joint name="wrist" parent="forearm" child="hand" 
                           xyz="0.3 0 0" rpy="0 0 0" 
                           effort="5." velocity="1." />

    <xacro:make_box_link name="hand" mass="0.3" size_x="0.1" size_y="0.1" size_z="0.1" />

    <!-- Gazebo plugin -->

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <legacyModeNS>false</legacyModeNS>
        </plugin>
    </gazebo>

</robot>